# Generated by Django 5.1.4 on 2024-12-29 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_user_listing_owner_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default='Інше', on_delete=django.db.models.deletion.SET_DEFAULT, to='ads.category'),
        ),
    ]
