# Generated by Django 5.1.4 on 2024-12-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_listing_category'),
    ]

    operations = [
    ]
