# Generated by Django 5.1.4 on 2025-01-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20241229_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
